baseURL = 'https://junaid.foo/'
languageCode = 'en-us'
title = 'Junaid Rahim'
theme = "typo"

# Disable tags, actually, they are rendered as a list, but the idea is to disable them.
disableKinds = ['taxonomy']

# Google analytics code
# googleAnalytics = "G-xxxxxxxxxx"

[params]
# Math mode
math = true
theme = "light"

# Intro on main page, content in markdown, if you omit title or content the other can be displayed
homeIntro = true
homeIntroTitle = 'Hello ☕️'
homeIntroContent = """
Just another [hacker](https://phrack.org/issues/7/3).

I'm currently working as a systems engineer at [Atlan](https://atlan.com) building the future of agentic data collaboration. 

Living in Bengaluru, India.

This website is a record of my work, talks, projects, musings, curiosities and research.

In my free time I love to write, read, cycle, travel and go on bike rides. I'm weirdly nerdy about PKM systems, fountain pens and street photography.

I've written a longer introduction [here](/about) if you're interested :)
"""

# Collection to display on home page: 
# in this case we would display content/posts pages
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Pagination size across all website, this is the same for homepage and single list page
paginationSize = 100

description = "This website is a record of my work, talks, projects, musings and research."

# Breadcrumbs
[params.breadcrumbs]
enabled = false

# Social icons
[[params.social]]
name = "x"
url = "https://x.com/junaidrahxm"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/junaidrahim"

[[params.social]]
name = "github"
url = "https://github.com/junaidrahim"


[[params.social]]
name = "instagram"
url = "https://instagram.com/junaidrahxm"


[[params.social]]
name = "telegram"
url = "https://t.me/zebion"

[[params.social]]
name = "strava"
url = "https://www.strava.com/athletes/50189743"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "drafts"
url = "/drafts"

[[params.menu]]
name = "talks"
url = "/talks"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "ai"
url = "/ai"


# Syntax highlight on code blocks, all styles: 
# https://xyproto.github.io/splash/docs/all.html
# I suggest algol
[markup]
[markup.highlight]
style = 'abap'

[outputs]
home = ['html', 'rss']